    <main>
      <div class="container mt-3">
        <h1>Сайты</h1>
        <table class="table table-hover table-bordered" data-test="urls">
          <tbody>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
            <?php foreach ($data as $url) : ?>
              <tr>
                <td><?= $url['id'] ?></td>
                <td>
                  <a href="<?= $router->urlFor('urls.show', ['id' => $url['id']]) ?>">
                    <?= $url['name'] ?>
                  </a>
                </td>
                <td><?= $url['last_check_created_at'] ?></td>
                <td><?= $url['status_code'] ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </main>