<!DOCTYPE html>
<html lang="ru" class="h-100">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark ps-1" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <main>
      <div class="container mt-3">
        <h1>Сайты</h1>
        <table class="table table-hover table-bordered" data-test="urls">
          <thead>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($data as $url) : ?>
              <tr>
                <td><?= htmlspecialchars($url['id']) ?></td>
                <td><a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                <td><?= isset($url['last_check_created_at']) ? htmlspecialchars($url['last_check_created_at']) : '' ?></td>
                <td><?= isset($url['status_code']) ? htmlspecialchars($url['status_code']) : '' ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </main>
  </body>

</html>