<?php include(__DIR__ . '/../header.phtml'); ?>

    <div>
      <?php if (isset($flash['success'])) : ?>
            <?php foreach ($flash['success'] as $message) : ?>
              <div class="alert alert-success" role="alert"><?= htmlspecialchars($message) ?></div>
            <?php endforeach ?>
      <?php elseif (isset($flash['warning'])) : ?>
            <?php foreach ($flash['warning'] as $message) : ?>
              <div class="alert alert-warning" role="alert"><?= htmlspecialchars($message) ?></div>
            <?php endforeach ?>
      <?php elseif (isset($flash['failure'])) : ?>
            <?php foreach ($flash['failure'] as $message) : ?>
              <div class="alert alert-danger" role="alert"><?= htmlspecialchars($message) ?></div>
            <?php endforeach ?>
      <?php endif ?>
    </div>
    <main>
      <div class="container mt-3">
        <h1>Сайт: <?= htmlspecialchars($name) ?></h1>
        <table class="table table-hover table-bordered" data-test="url">
          <tbody>
            <tr>
              <th>ID</th>
              <td><?= htmlspecialchars($id) ?></td>
            </tr>
            <tr>
              <th>Имя</th> 
              <td><?= htmlspecialchars($name) ?></td>
            </tr>
            <tr>
              <th>Дата создания</th>
              <td><?= htmlspecialchars($created_at) ?></td>
            </tr>
          </tbody>
        </table>
        <h2 class="mt-5 mb-3">Проверки</h2>
          <form action="/urls/<?= $id ?>/checks" method="post" class="mb-3">
              <input type="submit" class="btn btn-primary" value="Запустить проверку">
          </form>
          <table class="table table-hover table-bordered" data-test="checks">
            <tbody>
              <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
              </tr>
              <?php foreach ($urlChecks as $check) : ?>
                <tr>
                  <td><?= htmlspecialchars($check['id']) ?></td>
                  <td><?= isset($check['status_code']) ? htmlspecialchars($check['status_code']) : '' ?></td>
                  <td><?= isset($check['h1']) ? htmlspecialchars($check['h1']) : '' ?></td>
                  <td><?= isset($check['title']) ? htmlspecialchars($check['title']) : '' ?></td>
                  <td><?= isset($check['description']) ? htmlspecialchars($check['description']) : '' ?></td>
                  <td><?= htmlspecialchars($check['created_at']) ?></td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
      </div>
    </main>
  </body>
</html>
