    <main>
      <div class="container mt-3">
        <h1>Сайт: <?= $url['name'] ?></h1>
        <table class="table table-hover table-bordered" data-test="url">
          <tbody>
            <tr>
              <th>ID</th>
              <td><?= $url['id'] ?></td>
            </tr>
            <tr>
              <th>Имя</th> 
              <td><?= $url['name'] ?></td>
            </tr>
            <tr>
              <th>Дата создания</th>
              <td><?= $url['created_at'] ?></td>
            </tr>
          </tbody>
        </table>
        <h2 class="mt-5 mb-3">Проверки</h2>
          <form action="<?= $router->urlFor('urls.checks.store', ['url_id' => $url['id']]) ?>"
                  method="post" class="mb-3">
              <input type="submit" class="btn btn-primary" value="Запустить проверку">
          </form>
          <table class="table table-hover table-bordered" data-test="checks">
            <tbody>
              <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
              </tr>
              <?php foreach ($urlChecks as $check) : ?>
                <tr>
                  <td><?= $check['id'] ?></td>
                  <td><?= $check['status_code'] ?></td>
                  <td><?= $check['h1'] ?></td>
                  <td><?= $check['title'] ?></td>
                  <td><?= $check['description'] ?></td>
                  <td><?= $check['created_at'] ?></td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
      </div>
    </main>