<!DOCTYPE html>
<html lang="ru" class="h-100">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark ps-1" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div>
      <?php if (isset($flash['success'])) : ?>
          <?php foreach ($flash['success'] as $message) : ?>
              <div class="alert alert-success" role="alert"><?= htmlspecialchars($message) ?></div>
          <?php endforeach ?>
      <?php elseif (isset($flash['warning'])) : ?>
          <?php foreach ($flash['warning'] as $message) : ?>
              <div class="alert alert-warning" role="alert"><?= htmlspecialchars($message) ?></div>
          <?php endforeach ?>
      <?php elseif (isset($flash['failure'])) : ?>
          <?php foreach ($flash['failure'] as $message) : ?>
              <div class="alert alert-danger" role="alert"><?= htmlspecialchars($message) ?></div>
          <?php endforeach ?>
      <?php endif ?>
    </div>
    <main>
      <div class="container mt-3">
        <h1>Сайт: <?= htmlspecialchars($name) ?></h1>
        <table class="table table-hover table-bordered" data-test="url">
          <tbody>
            <tr>
              <th>ID</th>
              <td><?= htmlspecialchars($id) ?></td>
            </tr>
            <tr>
              <th>Имя</th> 
              <td><?= htmlspecialchars($name) ?></td>
            </tr>
            <tr>
              <th>Дата создания</th>
              <td><?= htmlspecialchars($created_at) ?></td>
            </tr>
          </tbody>
        </table>
        <h2 class="mt-5 mb-3">Проверки</h2>
          <form action="/urls/<?= $id ?>/checks" method="post" class="mb-3">
              <input type="submit" class="btn btn-primary" value="Запустить проверку">
          </form>
          <table class="table table-hover table-bordered" data-test="checks">
            <thead>
              <tr>
                <th>ID</th>
                <th>Код ответа</th>
                <th>h1</th>
                <th>title</th>
                <th>description</th>
                <th>Дата создания</th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($urlChecks as $check) : ?>
                <tr>
                  <td><?= htmlspecialchars($check['id']) ?></td>
                  <td><?= htmlspecialchars($check['status_code']) ?></td>
                  <td><?= htmlspecialchars($check['h1']) ?></td>
                  <td><?= htmlspecialchars($check['title']) ?></td>
                  <td><?= htmlspecialchars($check['description']) ?></td>
                  <td><?= htmlspecialchars($check['created_at']) ?></td>
                </tr>
              <?php endforeach ?>
            </tbody>
          </table>
      </div>
    </main>
  </body>

</html>