<?php include(__DIR__ . '/header.phtml'); ?>

    <main class="flex-grow-1">
      <div class="container my-3">
        <div class="p-5 mx-auto col-lg-8 bg-body-tertiary border rounded-3">
          <h1 class="display-3">Анализатор страниц</h1>
          <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
          <form class="row mb-3" action="/urls" method="post" required>
            <div class="col-8">
              <input
                type="text"
                name="url[name]"
                class="form-control form-control-lg
                    <?php if (isset($errors['name'])) : ?>
                      is-invalid
                    <?php endif ?>"
                aria-describedby="validationFeedback"
                placeholder="https://www.example.com">
              <?php if (isset($errors['name'])) : ?>
                <div id="validationFeedback" class="invalid-feedback"><?= htmlspecialchars($errors['name']) ?></div>
              <?php endif ?>
            </div>
            <div class="col-4">
              <input type="submit" class="btn btn-primary btn-lg px-5" value="ПРОВЕРИТЬ">
            </div>
          </form>
        </div>
      </div>
    </main>
  </body>
</html>
